output$cheatcode <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "cheatcode", "Indicateur de dérive imaginaire", .6)})
output$logloss <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "LogLoss", "Log Loss", threshold$LogLoss, top=T)})
output$auc_global <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "AUC_GLOBAL", "AUC Global", threshold$AUC)})
output$acc_global <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "ACC_GLOBAL", "ACC Global", threshold$ACC)})
output$kappa <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "Kappa", "Kappa de Cohen", threshold$Kappa)})
output$`taux-achat-top-100` <- renderAmCharts({makeMonitoringCharts(copy(scores_at_t()), "TauxAchat.TOP.100", "Taux d'achat dans les 100 client.e.s les mieux classé.e.s", threshold$TauxAch)})